### ISSUE TITLE
Plugin should exit if not called from the wiki

### ISSUE THREAD

**Issue by vidschofelix** [vidschofelix/epnsmartlink#1]
Add the missing line (if not defined [] die) an the beginnig of the action.php

Can be found  the dokuwiki-plugin example pages: https://www.dokuwiki.org/devel:action_plugins#sampleadd_always_a_javascript_file

**Comment by fishnux** [comment]
I have opened pull request https://github.com/vidschofelix/epnsmartlink/pull/2. Is this what you were expecting?

**Comment by vidschofelix** [comment]
exactly, perfect, thank you!
